### PR TITLE
Update ssd1306.cpp

### PR DESCRIPTION
**Pull request by ahmadexp**
add support for SSD1305

### CODE REVIEW

**Comment by ahmadexp** [comment]
@dwhinham, would you please consider this merge. This merge allows us to support the SSD1305 OLEDs

**Comment by dwhinham** [comment]
There is no need to ping me, I can see the PR just fine.

I have been sick with COVID for the last week and am starting to catch up.

There is zero documentation with this PR. It would have been nice to see some explanation of what it does and why you made the changes.

I will not be able to test this screen as I do not own the hardware.

**Comment by ahmadexp** [comment]
I have the explanation on the wiki side. I have tested it and I can assure it does not break anything.

**Comment by dwhinham** [comment]
I really don't like the way we are abusing the width parameter as a magic number to detect this display controller, as the width/height parameters in the config file are meant to represent how many user-facing pixels there are, not the size of the OLED's internal framebuffer. Hence, this commit breaks the pattern.

I will merge a similar commit to get the screen working for now, with additional notes to revisit this and try to clean it up in future.

I see the wiki content you have added, but the information about hacking the HATs etc. should probably should be moved to a separate page. It is useful information, but the page is meant to document displays only, so stuff about hacking the button wiring etc. is making it cluttered. I'll amend this shortly.

**Comment by ahmadexp** [comment]
For sure. I definitely agree with you. My thought was that making an entirely new file for a single value change was not reasonable.

**Pull request closed without merging**
